[package]
name = "sd"
version = "0.7.6"
edition = "2018"
authors = ["Gregory <gregory.mkv@gmail.com>"]
description = "An intuitive find & replace CLI"
readme = "README.md"
keywords = ["sed", "find", "replace", "regex"]
license = "MIT"
homepage = "https://github.com/chmln/sd"
repository = "https://github.com/chmln/sd.git"
categories = ["command-line-utilities", "text-processing", "development-tools"]

[dependencies]
regex = "1.4.3"
rayon = "1.5.0"
unescape = "0.1.0"
memmap2 = "0.5.10"
tempfile = "3.2.0"
thiserror = "1.0.24"
globwalk = "0.8.1"
ignore = "0.4.17"
ansi_term = "0.12.1"
is-terminal = "0.4.7"
clap = { version = "4.2.7", features = ["derive", "deprecated", "wrap_help"] }

[dev-dependencies]
assert_cmd = "1.0.3"
anyhow = "1.0.38"
rstest = "0.17.0"

[build-dependencies]
clap = "4.2.7"
clap_complete = "4.2.2"
man = "0.3.0"

[profile.release]
opt-level = 3
lto = true
